version: "3"

services:
  react:
    container_name: "react-app"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
      - type: volume
        source: node_modules
        target: /usr/src/app/node_modules
    command: yarn start
    ports:
      - "3000:3000"

volumes:
  node_modules:
